# Generated by Django 2.2 on 2020-10-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('daily_price', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.City')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Property')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Reservation')),
            ],
        ),
    ]
