# Generated by Django 2.2 on 2020-10-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dormitories',
            field=models.IntegerField(default=0),
        ),
    ]
