# Generated by Django 2.2 on 2020-10-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_property_dormitories'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rental.Property'),
        ),
        migrations.AlterField(
            model_name='reservationdates',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.Reservation'),
        ),
    ]
