# Generated by Django 2.2 on 2020-10-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20201027_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationDates',
            new_name='ReservationDate',
        ),
    ]
