# Generated by Django 2.2 on 2020-10-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20201027_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservationdate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
