# Generated by Django 2.2 on 2020-10-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('rental', '0007_auto_20201027_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
    ]
