# Generated by Django 2.2 on 2020-10-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('rental', '0008_property_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='services',
        ),
        migrations.CreateModel(
            name='PropertyServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Property')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'order_with_respect_to': 'property',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(through='rental.PropertyServices', to='services.Service'),
        ),
    ]
