# Generated by Django 2.2 on 2020-10-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20201027_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='services',
        ),
        migrations.DeleteModel(
            name='PropertyServices',
        ),
    ]
