# Generated by Django 2.2 on 2020-10-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_property'),
        ('rental', '0011_propertyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(blank=True, through='rental.PropertyService', to='services.Service'),
        ),
    ]
