# Generated by Django 2.2 on 2020-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_property_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='services'
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
        migrations.DeleteModel(
            name='PropertyService',
        ),
    ]
