# Generated by Django 2.2 on 2020-10-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_auto_20201027_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
