# Generated by Django 2.2 on 2020-10-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_auto_20201027_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
