# Generated by Django 2.2 on 2020-10-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_property_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='img',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.PropertyImage'),
        ),
    ]
