# Generated by Django 2.2 on 2020-10-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_auto_20201028_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='short_description',
            field=models.CharField(default='', max_length=70),
        ),
    ]
