# Generated by Django 2.2 on 2020-10-28 05:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_auto_20201028_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='images/properties'), upload_to=''),
        ),
    ]
