# Generated by Django 2.2 on 2020-10-28 05:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_auto_20201028_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='static/img/properties'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='short_description',
            field=models.CharField(default='', max_length=70, null=True),
        ),
    ]
