# Generated by Django 2.2 on 2020-10-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_auto_20201028_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
