# Generated by Django 2.2 on 2020-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_auto_20201028_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(null=True, to='services.Service'),
        ),
    ]
