# Generated by Django 2.2 on 2020-10-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_auto_20201028_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.Service'),
        ),
    ]
