# Generated by Django 2.2 on 2020-10-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0028_auto_20201028_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_dates', to='rental.Property'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_dates', to='rental.Reservation'),
        ),
    ]
