# Generated by Django 2.2 on 2020-10-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_auto_20201029_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_dates', to='rental.Reservation'),
        ),
    ]
