# Generated by Django 2.2 on 2020-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_propertyservice'),
        ('services', '0002_service_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='property',
        ),
        migrations.AddField(
            model_name='service',
            name='property',
            field=models.ManyToManyField(blank=True, through='rental.PropertyService', to='rental.Property'),
        ),
    ]
